### PR TITLE
fix: change Address to AddressBase32

### PR DESCRIPTION
**Pull request by AnthonyLaw**
### Fix
- Change Address to AddressBase32 format.
- Handle Namespace id and address base 32 on `UnresolvedAddress` field.
- Removed AddressBase32 schemas.

Resolved: #182

### CODE REVIEW

**Comment by fboucquez** [comment]
Do we need an `AddressBase32` type? It seems like we are moving all the addresses to Base32. What if we do the opposite, Used the `Address` name for all base32? So we have only one `Address` which is the Base32 "NASYMBOLLK6FSL7GSEMQEAWN7VW55ZSZU25TBOA"

**Comment by fboucquez** [comment]
ResolutionEntryDTO and MetadataEntryDTO are still using the hex address. Should they be the base32? 

https://github.com/AnthonyLaw/symbol-openapi/blob/Task/182_address_formatting/spec/plugins/receipt/schemas/ResolutionEntryDTO.yml#L10

https://github.com/AnthonyLaw/symbol-openapi/blob/Task/182_address_formatting/spec/plugins/metadata/schemas/MetadataEntryDTO.yml#L16

Once those are resolved, the old Address.yml is not used anymore, so the AddressBase32 could become the new Address?

**Comment by Jaguar0625** [comment]
why do we want to rename this to `AddressBase32`. Calling it `Address` makes more sense to me. 

the current address format probably shouldn't be used anymore, so there wouldn't be a conflict. if it's still needed, i'd prefer to call it something like DecodedAddress or AddressHex

**Comment by segfaultxavi** [comment]
> if it's still needed, i'd prefer to call it something like DecodedAddress or AddressHex

Small nitpick, I'd prefer `RawAddress` (or `RawAddressHex`) rather than `DecodedAddress`, as the latter suggests that the address has been previously encoded.

**Comment by fboucquez** [comment]
We would like to change rest to only return encoded addresses, no raw hex anymore. We can unify both open api addresses files into one. I would call it Address.

**Comment by AnthonyLaw** [comment]
In early, I thought just remain because we have not a clear decision for it.
Right now we have decided, so call it `Address` will be best.

I will do the update, thanks for the review and feedback.

**Review by Jaguar0625 — APPROVED** [review]

**Review by Jaguar0625 — APPROVED** [review]

**Pull request merged**
